-- ==============================================================================
-- BEESHIP SUPABASE DATABASE SCHEMA
-- ==============================================================================

-- 1. Create custom types
DO $$ BEGIN CREATE TYPE public.user_role AS ENUM ('ADMIN', 'SHIPPER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.driver_status AS ENUM ('OFFLINE', 'IDLE', 'PICKING_UP', 'DELIVERING'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.order_status AS ENUM ('PENDING', 'ACCEPTED', 'COMPLETED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.payment_method_type AS ENUM ('CASH', 'TRANSFER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.surcharge_type AS ENUM ('FIXED', 'MULTIPLIER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 2. Create tables
-- 2.1. services (from existing system)
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    base_price NUMERIC NOT NULL,
    base_km NUMERIC NOT NULL,
    per_km_price NUMERIC NOT NULL
);

-- 2.2. surcharges (from existing system)
CREATE TABLE IF NOT EXISTS public.surcharges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type public.surcharge_type NOT NULL,
    value NUMERIC NOT NULL,
    is_active BOOLEAN DEFAULT true
);

-- 2.3. user_roles (links to auth.users)
CREATE TABLE IF NOT EXISTS public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role public.user_role NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_auth_user_id UNIQUE (auth_user_id)
);

-- 2.4. drivers
CREATE TABLE IF NOT EXISTS public.drivers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    full_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    status public.driver_status DEFAULT 'OFFLINE'::public.driver_status NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.5. orders
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_phone TEXT NOT NULL,
    origin TEXT NOT NULL,
    destination TEXT NOT NULL,
    price NUMERIC NOT NULL,
    payment_method public.payment_method_type NOT NULL,
    status public.order_status DEFAULT 'PENDING'::public.order_status NOT NULL,
    driver_id UUID REFERENCES public.drivers(id) ON DELETE SET NULL,
    proof_image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.6. chat_rooms
CREATE TABLE IF NOT EXISTS public.chat_rooms (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    driver_id UUID NOT NULL REFERENCES public.drivers(id) ON DELETE CASCADE,
    last_message TEXT,
    last_message_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_driver_room UNIQUE (driver_id)
);

-- 2.7. chat_messages
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    sender_role public.user_role NOT NULL,
    message_text TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Setup Row Level Security (RLS)
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.surcharges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- Disable RLS fully for simplicity during development, or configure specifically.
-- Below policies allow anonymous/authenticated full access to speed up MVP. 
-- IN PRODUCTION, RESTRICT THESE USING role CHECKS.
DROP POLICY IF EXISTS "Allow all operations for authenticated users" ON public.services;
CREATE POLICY "Allow all operations for authenticated users" ON public.services FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all operations for authenticated users" ON public.surcharges;
CREATE POLICY "Allow all operations for authenticated users" ON public.surcharges FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all operations for authenticated users" ON public.user_roles;
CREATE POLICY "Allow all operations for authenticated users" ON public.user_roles FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all operations for authenticated users" ON public.drivers;
CREATE POLICY "Allow all operations for authenticated users" ON public.drivers FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all operations for authenticated users" ON public.orders;
CREATE POLICY "Allow all operations for authenticated users" ON public.orders FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all operations for authenticated users" ON public.chat_rooms;
CREATE POLICY "Allow all operations for authenticated users" ON public.chat_rooms FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all operations for authenticated users" ON public.chat_messages;
CREATE POLICY "Allow all operations for authenticated users" ON public.chat_messages FOR ALL USING (auth.role() = 'authenticated');

-- Fallbacks if app needs public access during dev (not recommended for production)
-- ... 

-- 4. Set up Realtime publications
-- By default, realtime might not be enabled for new tables. You must add them to the publication.
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.drivers; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.orders; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_rooms; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_messages; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 5. Helper Functions / Triggers (Optional)
-- Auto-update updated_at on drivers
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_drivers_modtime ON public.drivers;
CREATE TRIGGER update_drivers_modtime
    BEFORE UPDATE ON public.drivers
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- ==============================================================================
-- 6. TẠO TÀI KHOẢN MẪU (DUMMY DATA)
-- Chạy block này sẽ tự động tạo 2 tài khoản: 
-- 1. Admin (admin@beeship.com / 123456)
-- 2. Shipper (shipper@beeship.com / 123456)
-- ==============================================================================
DO $$
DECLARE
  admin_uid UUID := '11111111-1111-1111-1111-111111111111';
  shipper_uid UUID := '22222222-2222-2222-2222-222222222222';
BEGIN
  -- Insert Admin User (Password: 123456)
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'admin@beeship.com') THEN
    INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
    VALUES (admin_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'admin@beeship.com', crypt('123456', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{}', now(), now());
  END IF;

  -- Insert Shipper User (Password: 123456)
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'shipper@beeship.com') THEN
    INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
    VALUES (shipper_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'shipper@beeship.com', crypt('123456', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{}', now(), now());
  END IF;
  
  -- Assign roles (admin_uid -> ADMIN, shipper_uid -> SHIPPER)
  INSERT INTO public.user_roles (auth_user_id, role)
  VALUES (admin_uid, 'ADMIN'), (shipper_uid, 'SHIPPER')
  ON CONFLICT (auth_user_id) DO NOTHING;

  -- Create Driver profile for Shipper
  INSERT INTO public.drivers (auth_user_id, full_name, phone_number, status)
  SELECT shipper_uid, 'Trần Tài Xế (Mẫu)', '099' || floor(random() * 10000000)::text, 'OFFLINE'
  WHERE NOT EXISTS (SELECT 1 FROM public.drivers WHERE auth_user_id = shipper_uid);
  
END $$;

-- ==============================================================================
-- 7. THÊM DỮ LIỆU DỊCH VỤ VÀ PHỤ PHÍ (SERVICES & SURCHARGES)
-- Dữ liệu cơ bản cho hệ thống BeeShip
-- ==============================================================================

-- Xóa dữ liệu cũ nếu có để tránh trùng lặp khi chạy lại nhiều lần
TRUNCATE TABLE public.services RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.surcharges RESTART IDENTITY CASCADE;

-- Thêm dữ liệu Services
INSERT INTO public.services (id, name, base_price, base_km, per_km_price) VALUES
(2, 'Giao hàng', 12000, 2, 5000),
(3, 'Chạy xe hộ', 25000, 2, 7000),
(4, 'Ship đồ ăn', 15000, 2, 5000),
(5, 'Xe ôm công nghệ', 20000, 3, 5000),
(6, 'Giao bánh kem', 20000, 2, 5000),
(7, 'SHOP 15K', 15000, 3, 5000);

-- Thêm dữ liệu Surcharges
INSERT INTO public.surcharges (id, name, type, value, is_active) VALUES
(1, 'Mưa lớn', 'FIXED', 3000, TRUE),
(4, 'quãng đường trên 15km', 'MULTIPLIER', 1.2, TRUE);

-- ==============================================================================
-- 8. TẠO BUCKET LƯU TRỮ HÌNH ẢNH (STORAGE)
-- Bucket: proofs (Dùng để lưu ảnh bằng chứng giao hàng)
-- ==============================================================================

INSERT INTO storage.buckets (id, name, public) 
VALUES ('proofs', 'proofs', true)
ON CONFLICT (id) DO NOTHING;

-- Cho phép ai cũng có thể xem ảnh (Public Access)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'proofs' );

-- Cho phép user đã đăng nhập (Shipper) được upload ảnh
DROP POLICY IF EXISTS "Authenticated users can upload" ON storage.objects;
CREATE POLICY "Authenticated users can upload" 
ON storage.objects FOR INSERT 
WITH CHECK ( bucket_id = 'proofs' AND auth.role() = 'authenticated' );
